<div class="account-login unloq-login">
    <div class="col-1">
        <div class="content">
            <div>
                <h2><?php echo $this->__('Login with UNLOQ'); ?></h2>
            </div>
            <div class="login-box">
                <script type="text/javascript" src="<?php echo $this->getPluginUrl(); ?>" data-unloq-key="<?php echo $this->getApiKey(); ?>" data-unloq-theme="<?php echo $this->getTheme(); ?>"></script>
            </div>
        </div>
    </div>
</div>
